name: my workflow
on: [workflow_dispatch, push]
jobs:
  my-first-job:
    env:
      MY_ENV_VAR: "my env var value"
    runs-on: ubuntu-latest
    steps:
        - run: echo ${{vars.MYVAR}}
        - run: echo ${{env.MYSECREAT}}
        
