name: my workflow
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
        - name: print cpu info
          run: |
           lscpu
           nproc
           free -h
