name: my workflow
on: 
  push:
    branches: [main,dev]
jobs:
     
  my-first-job:
    if: 5>3
    runs-on: ubuntu-latest
    steps:
        - run: echo "run first job"
  my-second-job:
    if: 5<3
    runs-on: ubuntu-latest
    steps:
        - run: echo "run second job"
        
